from enum import Enum


class MovieField(Enum):
    SELECT_FIELDS = "selectFields"
    SORT_FIELD = "sortField"
    SORT_TYPE = "sortType"
    PAGE = "page"
    LIMIT = "limit"
    ID = "id"
    EXTERNAL_ID_KP_HD = "externalId.kpHD"
    EXTERNAL_ID_IMDB = "externalId.imdb"
    EXTERNAL_ID_TMDB = "externalId.tmdb"
    NAME = "name"
    ALTERNATIVE_NAME = "alternativeName"
    NAMES_NAME = "names.name"
    TYPE = "type"
    TYPE_NUMBER = "typeNumber"
    YEAR = "year"
    DESCRIPTION = "description"
    SHORT_DESCRIPTION = "shortDescription"
    SLOGAN = "slogan"
    STATUS = "status"
    RATING_KP = "rating.kp"
    RATING_IMDB = "rating.imdb"
    RATING_TMDB = "rating.tmdb"
    RATING_FILM_CRITICS = "rating.filmCritics"
    RATING_RUSSIAN_FILM_CRITICS = "rating.russianFilmCritics"
    RATING_AWAIT = "rating.await"
