from enum import Enum


class PersonField(Enum):
    SELECT_FIELDS = "selectFields"
    SORT_FIELD = "sortField"
    SORT_TYPE = "sortType"
    PAGE = "page"
    LIMIT = "limit"
    ID = "id"
    NAME = "name"
    EN_NAME = "enName"
    PHOTO = "photo"
    SEX = "sex"
    GROWTH = "growth"
    BIRTHDAY = "birthday"
    DEATH = "age"
    BIRTH_PLACE_VALUE = "birthPlace.value"
    DEATH_PLACE_VALUE = "deathPlace.value"
    SPOUSES_ID = "spouses.id"
    SPOUSES_NAME = "spouses.name"
    SPOUSES_DIVORCED = "spouses.divorced"
    SPOUSES_DIVORCED_REASON = "spouses.divorcedReason"
    SPOUSES_SEX = "spouses.sex"
    SPOUSES_RELATION = "spouses.relation"
    COUNT_AWARDS = "countAwards"
    PROFESSION_VALUE = "profession.value"
    FACTS_VALUE = "facts.value"
    MOVIES_ID = "movies.id"
    MOVIES_NAME = "movies.name"
    MOVIES_ALTERNATIVE_NAME = "movies.alternativeName"
    MOVIES_RATING = "movies.rating"
    MOVIES_GENERAL = "movies.general"
    MOVIES_DESCRIPTION = "movies.description"
    MOVIES_EN_PROFESSION = "movies.enProfession"
